#!/bin/bash
#
# $GBIF_AUTH must be set to the download.gbif.org user.
#

cd $(dirname $(realpath $0))

function waitDl() {
  while [[ $(curl -Ss --user $GBIF_AUTH 'https://api.gbif.org/v1/occurrence/download/user/download.gbif.org?status=PREPARING&status=RUNNING' | jq -r .count) -ge $1 ]]; do
    sleep 1m
  done
}

for i in \
  monthly-everything-mol.json \
  cloud-upload-simple-parquet.json \
  monthly-everything-csv.json monthly-everything-dwc.json \
  monthly-ebird-csv.json monthly-present-csv.json monthly-georeferenced-csv.json monthly-georeferenced-present-csv.json \
  monthly-ebird-dwc.json monthly-present-dwc.json monthly-georeferenced-dwc.json monthly-georeferenced-present-dwc.json
do
  waitDl 3
  echo "Starting download '$i'"
  curl -Ssi --user $GBIF_AUTH -H "Content-Type: application/json" -X POST -d @$i 'https://api.gbif.org/v1/occurrence/download/request'
  echo
  echo
  sleep 1m
done

echo
echo "Monthly downloads completed."
