#!/bin/zsh -e

for i in test-download-format-*.json(oe:REPLY=\$RANDOM:); do
  echo $i
  until curl -f --user $GBIF_AUTH -H "Content-Type: application/json" -X POST -d @$i 'https://api.gbif-dev.org/v1/occurrence/download/request'; do
    sleep 15
  done
  echo
  sleep 5
done
