# Simple image that copy the already previous builds shaded jar into a specific location.
# This is used for SparkApplications to have a simple way to access the artifacts during their execution
#FROM stackable/hadoop:3.3.4-stackable23.11.0
FROM stackable/hive:3.1.3-stackable24.3.0
ARG JAR_FILE=${JAVA_JAR_FILE}

ARG DOWNLOAD_ID=""
ARG CORE_TERM=""
ARG DOWNLOAD_PROPERTIES_FILE_PATH=""
ARG DOWNLOAD_STAGE=""

USER root
RUN mkdir /jobs
COPY --chown=1000:1000 "./target/${JAR_FILE}" "/jobs/occurrence-download.jar"
USER gbif

CMD java $JVM_OPTIONS \
    -cp /jobs/occurrence-download.jar \
    org.gbif.occurrence.download.spark.GbifOccurrenceDownloads \
    $DOWNLOAD_ID \
    $CORE_TERM \
    $DOWNLOAD_PROPERTIES_FILE_PATH \
    $DOWNLOAD_STAGE

