# Simple image that copy the already previous builds shaded jar into a specific location.
# This is used for SparkApplications to have a simple way to access the artifacts during their execution
#FROM stackable/hadoop:3.3.4-stackable23.11.0
FROM docker.stackable.tech/stackable/spark-k8s:3.5.1-stackable24.3.0
ARG JAR_FILE=${JAVA_JAR_FILE}

ENV DOWNLOAD_ID=""
ENV CORE_TERM=""
ENV DOWNLOAD_PROPERTIES_FILE_PATH=""
ENV DOWNLOAD_STAGE=""

USER root
RUN mkdir /jobs
COPY --chown=1000:1000 "./target/${JAR_FILE}" "/jobs/occurrence-download.jar"
CMD java $JVM_OPTIONS \
    -cp /jobs/occurrence-download.jar:/stackable/spark/jars/* \
    org.gbif.occurrence.download.spark.GbifOccurrenceDownloads \
    $DOWNLOAD_ID \
    $CORE_TERM \
    $DOWNLOAD_PROPERTIES_FILE_PATH \
    $DOWNLOAD_STAGE

