package org.gbif.occurrence.search.es;

/** Enum that contains the mapping of symbolic names and field names of valid Solr fields. */
public enum OccurrenceEsField {
  KEY("key"),
  LATITUDE("decimallatitude"),
  LONGITUDE("decimallongitude"),
  COUNTRY("country"),
  COUNTRY_CODE("countrycode"),
  PUBLISHING_COUNTRY("publishingcountry"),
  CONTINENT("continent"),
  YEAR("year"),
  MONTH("month"),
  DAY("day"),
  CATALOG_NUMBER("catalognumber"),
  RECORDED_BY("recordby"),
  RECORD_NUMBER("recordnumber"),
  BASIS_OF_RECORD("basisofrecord"),
  DATASET_KEY("datasetkey"),
  TAXON_KEY("taxakey"),
  UNIQUE_TAXON_KEY("taxonkey"),
  TAXON_RANK("taxonrank"),
  KINGDOM_KEY("kingdomkey"),
  KINGDOM("kingdom"),
  PHYLUM_KEY("phylumkey"),
  PHYLUM("phylum"),
  CLASS_KEY("classkey"),
  CLASS("class"),
  ORDER_KEY("orderkey"),
  ORDER("order"),
  FAMILY_KEY("familykey"),
  FAMILY("family"),
  GENUS_KEY("gbifGenusKey"),
  GENUS("genus"),
  SUBGENUS_KEY("subgenuskey"),
  SUBGENUS("subgenus"),
  SPECIES_KEY("specieskey"),
  SPECIES("species"),
  SCIENTIFIC_NAME("scientificname"),
  SPECIFIC_EPITHET("specificepithet"),
  INFRA_SPECIFIC_EPITHET("infraspecificepithet"),
  GENERIC_NAME("genericname"),
  COLLECTION_CODE("collectioncode"),
  ELEVATION("elevation"),
  DEPTH("depth"),
  INSTITUTION_CODE("institutioncode"),
  SPATIAL_ISSUES("hasgeospatialissues"),
  HAS_COORDINATE("hascoordinate"),
  EVENT_DATE("eventdate"),
  LAST_INTERPRETED("lastinterpreted"),
  LAST_CRAWLED("lastcrawled"),
  LAST_PARSED("lastparsed"),
  TYPE_STATUS("typestatus"),
  MEDIA_TYPE("mediatype"),
  ISSUE("issue"),
  ESTABLISHMENT_MEANS("establishmentmeans"),
  OCCURRENCE_ID("occurrenceid"),
  FULL_TEXT(""),
  REPATRIATED("repatriated"),
  ORGANISM_ID("organismid"),
  STATE_PROVINCE("stateprovince"),
  WATER_BODY("waterbody"),
  LOCALITY("locality"),
  PROTOCOL("protocol"),
  LICENSE("license"),
  CRAWL_ID("crawlid"),
  PUBLISHING_ORGANIZATION_KEY("publishingorgkey"),
  INSTALLATION_KEY("installationkey"),
  NETWORK_KEY("networkkey"),
  EVENT_ID("eventid"),
  PARENT_EVENT_ID("parenteventid"),
  SAMPLING_PROTOCOL("samplingprotocol"),
  COORDINATE_PRECISION("coordinateprecision"),
  COORDINATE_UNCERTAINTY_METERS("coordinateuncertaintyinmeters"),
  DATE_IDENTIFIED("dateidentified"),
  INDIVIDUAL_COUNT("individualcount"),
  LIFE_STAGE("lifestage"),
  MODIFIED("modified"),
  REFERENCES("references"),
  SEX("sex"),
  COORDINATE_ACCURACY("coordinateaccuracy"),
  ELEVATION_ACCURACY("elevationaccuracy"),
  DEPTH_ACCURACY("depthaccuracy"),
  IDENTIFIER("identifier"),
  RELATION("relation"),
  TYPIFIED_NAME("typifiedname");

  private final String fieldName;

  OccurrenceEsField(String fieldName) {
    this.fieldName = fieldName;
  }

  /** @return the fieldName */
  public String getFieldName() {
    return fieldName;
  }
}
